services:
  database:
    image: postgres
    container_name: nlw-valoriza
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nlwvaloriza
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
